### ISSUE TITLE
Error libcrypto when building AOSP for RPi4

### ISSUE THREAD

**Issue by trungkstn** [android-rpi/device_arpi_rpi4#124]
> error: libcrypto's ABI has EXTENDING CHANGES. Please check compatibility report at: out/soong/.intermediates/external/boringssl/libcrypto/android_vendor.34_arm64_armv8-a_cortex-a72_shared/libcrypto.so.abidi
> ff
> 
> error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py -l libcrypto
> 

https://github.com/android-rpi/device_arpi_rpi4
Host; Ubuntu 22.04 LTS

I get this issue but can't find any solution to fix it. Can anyone help me to fix it?

Thank you.

**Comment by losgobbi** [comment]
This is strange because recently I've builded this project for my pi4 without errors. I've used the Ubuntu too, 22.04.3 LTS. Searching over for this particular error, I can see other reports from other people. Did you have a chance to build successfully or always faced that error? Did you tried to update the ABI as the command suggest (create_reference_dumps.py)?
Tks.

**Comment by trungkstn** [comment]
I have never had a successful build. Currently I switched to using Android 12 for RPi4. Perhaps this ticket should be closed. I will try again next time.
